name: Pipeline for Python Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest -vv --cov=. --cov-report=html --cov-config=.coveragerc
        ls

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: calculator-test-report
        path: htmlcov/

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 app/ --count --show-source --statistics

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Python Package
      run: |
        pip install build
        python -m build

    - name: Upload Python Package to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: calculator-build
        path: dist/
